name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.TOKEN_FLY }}
jobs:
  # This workflow contains multiple jobs
  push_docker:
      name: Push Image in DockerHub
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      # build docker image and push to docker hub
      # only if the app build and test successfully
      # needs: [build_test]
      steps:           
        - name: checkout repo
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.USER_DOCKER }}
            password: ${{ secrets.TOKEN_DOCKER }}
      
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.USER_DOCKER }}/api-service-order:1.1.1
  deploy_app_fly:
      name: Deploy App on Fly
      runs-on: ubuntu-latest
      steps:           
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Setup Flyctl
          uses: superfly/flyctl-actions/setup-flyctl@master

        - name: Exec chmod app
          id: chmod_app
          run: chmod 777 ./

        - name: Exec chmod newApp
          id: chmod_launch_app
          run: chmod 777 ./newApp.sh

        - name: Exec newApp
          id: launch_app
          run: ./newApp.sh

        - name: Deploy App
          id: deploy_app
          run: flyctl deploy
  validate:
      name: Vallidate App
      runs-on: ubuntu-latest
      needs: [deploy_app_fly]
      steps:           
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Setup Flyctl
          uses: superfly/flyctl-actions/setup-flyctl@master

        - name: Exec chmod app
          id: chmod_app
          run: chmod 777 ./
        
        - name: Exec chmod validate
          id: chmod_validate
          run: chmod 777 ./validate.sh

        - name: Exec Scale
          id: validate_app
          run: ./validate.sh
        
